"""Add genders to the users model

Revision ID: b332b34efc03
Revises: 36143692b2bb
Create Date: 2024-04-01 20:45:54.207692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b332b34efc03'
down_revision = '36143692b2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_genders', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('number_of_genders')

    # ### end Alembic commands ###
